spring.application.name=core-ledger
server:
port: 8080

spring:
application:
name: core-ledger

datasource:
url: jdbc:postgresql://localhost:5432/ledger_db
username: ledger_admin
password: ledger_2026
driver-class-name: org.postgresql.Driver

jpa:
hibernate:
ddl-auto: update
show-sql: true
properties:
hibernate:
format_sql: true
dialect: org.hibernate.dialect.PostgreSQLDialect

data:
redis:
host: localhost
port: 6379

kafka:
bootstrap-servers: localhost:9092
consumer:
group-id: core-ledger-group
auto-offset-reset: earliest
key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
producer:
key-serializer: org.apache.kafka.common.serialization.StringSerializer
value-serializer: org.apache.kafka.common.serialization.StringSerializer
